### ISSUE TITLE
Naming scheme for new custom classifications

### ISSUE THREAD

**Issue by nheeren** [IndEcol/IEDC_tools#1]
@stefanpauliuk I am currently writing the function that determines the name of new custom classifications. During our call we said we would use a concatenation of the dataset name and the aspect name. An example: `1_F_steel_SankeyFlows_2008_Global_﻿origin_process`.

However, I suggest to i. reverse the order, because it is makes it clearer what kind of classification this is supposed to be, ii. use two underscores to distinguish the names from another. So the example would become: `﻿origin_process__1_F_steel_SankeyFlows_2008_Global`.

Was wondering if there might be a reason not to do so...?

**Comment by stefanpauliuk** [comment]
Good idea, OK!
